services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: admin 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin 
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  python_app:
    build: ./python-app 
    ports:
      - "5000:5000" 
    environment: 
      REDIS_HOST: redis 
      REDIS_PORT: 6379
      REDIS_QUEUE_NAME: garden_actions 
    depends_on:
      - redis





volumes:
  postgres_data:
